module.exports = {
    angular: true,
    _: true,
    d3: true,
    $: true,
    Notification: true,
    LocalizationProvider: true,
    JL: true,
    H: true,
    ModuleRegister: true,
    PDFJS: true,
    PackageData: true,
    GroupPackages: true,
    ScrollHandler: true,
    Snap: true,
    UrlCreator: true,
    removeResizeListener: true,
    addResizeListener: true,
    tinyMCE: true,
    slugg: true,
}